# schema: https://scanner.dev/schema/scanner-detection-rule.v1.json
name: Cloudtrail SecretsManager secret retrieved from AWS CloudShell environment
description: |-
  ## Goal
  Detect when an AWS secret is retrieved from a CloudShell environment.

  ## Strategy
  Monitor CloudTrail for retrieval of AWS secrets from CloudShell. The threat group LUCR-3 uses CloudShell in the AWS management console to interact with the AWS API and retrieve secrets.

  ## Triage and Response
  1. Determine if the user performed this operation.
  2. If the API calls were not made by the user:
     * Rotate user credentials.
     * Rotate the retrieved secrets, if feasible.
     * Investigate other API calls made by the user.
     * Initiate your organization's incident response process.
enabled: true
severity: Medium
query_text: |-
  %ingest.source_type:cloudtrail
  userAgent:*exec-env/CloudShell*
  eventName:GetSecretValue
  | groupbycount(userIdentity.arn)
  | where @q.count > 0
time_range_s: 300
run_frequency_s: 60
event_sink_keys:
- medium_severity_alerts
tags:
- techniques.t1555.credentials_from_password_stores
- tactics.ta0006.credential_access
- source.cloudtrail
